### ISSUE TITLE
Import Doc for chrome is outdated

### ISSUE THREAD

**Issue by isbaral** [bitwarden/help#27]
As of v61 they removed the flag for disabling md-settings please offer another work around.

Thanks,
Israel

**Comment by kspearrin** [comment]
62 is suppose to add back the ability to export so we'll see.

**Comment by isbaral** [comment]
![image](https://user-images.githubusercontent.com/33637501/32901627-eb6fafea-cab5-11e7-8da1-93fd82356220.png)
 and I can't find it anywhere

**Comment by kspearrin** [comment]
Read through this topic. I'm not sure what the latest news is actually: https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!topic/chrome/99KZmH2DRrA

**Comment by isbaral** [comment]
gotcha, looks like it won't hit stable until next month. 
you can close this I guess.

**Comment by kspearrin** [comment]
I imagine the docs may need to change though? So you know the new procedure with 62?

**Comment by isbaral** [comment]
I can't find it in 62, I think it'll be in 63.

**Comment by kspearrin** [comment]
Ok. Good to know.

**Comment by Vixine** [comment]
Now that Chrome 63 is out you can update the article to say that it is now possible again to export passwords. 

Steps are as follows: 
1. Go to chrome://flags/#password-import-export
2. Select enabled
3. Relaunch chrome
4. Go to chrome://settings/passwords
5. Select export (I'd include a screenshot here because it's not immediately obvious where it is).
6. Follow import steps.

**Comment by kspearrin** [comment]
@Vixine Thanks. I restored the original instructions: https://help.bitwarden.com/article/import-from-chrome/
