### ISSUE TITLE
Specify bwdc data-file - Directory Connector

### ISSUE THREAD

**Issue by haneef95** [bitwarden/help#340]
Hi,

I understand that the `bwdc data-file` command could be used to check the absolute path of the `data.json` file.

> The `data-file` command returns an absolute path to the `data.json` database file used by the Directory Connector CLI.

https://github.com/bitwarden/help/blame/master/_articles/directory-connector/directory-sync.md#L237

Are there any commands to specify a data-file instead?

Kind regards,

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
