### ISSUE TITLE
What is 'Overwrite existing organization users based on current sync settings' in BWDC?

### ISSUE THREAD

**Issue by haneef95** [bitwarden/help#341]
Hi,

One of the Sync Options reads: `Overwrite existing organization users based on current sync settings` in the Bitwarden Directory Connector Settings tab.
https://github.com/bitwarden/help/blame/master/_articles/directory-connector/directory-sync.md#L77
![image](https://user-images.githubusercontent.com/298208/103566182-73951b00-4eb9-11eb-835b-5938834e2e14.png)

1. What does this do?
2. Does this only affect the user entry within the organisation or would it affect the user entry in the whole installation?

Thanks,

**Comment by clayadams5226** [comment]
Hey @haneef95 Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
