### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Pouggy** [bitwarden/help#418]
So, you have created a folder.  Then what?  No explanation of what to do next.

**Comment by fschillingeriv** [comment]
The next step would be to add a Vault item to one, you can find info on that [here](https://bitwarden.com/help/article/getting-started-webvault/#first-steps) and [here](https://bitwarden.com/help/article/managing-items/#add-a-vault-item).

Assuming this issue is opened regarding https://bitwarden.com/help/article/folders/, which we can add to to make more explicit.
