### ISSUE TITLE
Payment plan per month

### ISSUE THREAD

**Issue by sjoerdapp** [bitwarden/help#441]
Suggestion or Edit for: bitwarden.com/help/

**Comment by fschillingeriv** [comment]
@sjoerdapp A bit unclear what this issue is for, if you're hoping to make a feature request, that's best done on the community forums: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.

Otherwise, I'll need a bit more info on the suggestion being made. Thanks!

**Comment by d6gNMGiKx6k8** [comment]
Not OP, but I suspect it is the confusion of referencing a "per month" cost, but that for non-Teams/non-Enterprise accounts, there is no "per month" billing.  

Only Teams and Enterprises have a per-month billing option.  Individual and Family accounts only have an annual billing, yet reference the cost if it was to be paid per month (but it can't be paid per month).  

I believe the suggestion is to allow a payment per month for individuals and/or families.  If there are no plans to change billing options, then maybe a sentence that says "billing is done for one year at a time for individuals and families, there is no month-to-month billing as month-to-month billing is only an option for teams and enterprises" would help clarify further.  

Otherwise, without further clarification, I'd close this request as there is no plans to change anything for billing plans at this point in time.
