### ISSUE TITLE
Getting started, vs mechanical steps

### ISSUE THREAD

**Issue by sumatra54** [bitwarden/help#442]
Suggestion or Edit for: bitwarden.com/help/article/getting-started-desktop/

Rather than give us step-by-step mechanics in "getting started", tell me how to use it, what good is it, what can I do with it.  Why would I use the desktop app vs a browser extension?  Can I sync between devices using the desktop app, or do I have to use a browser extension?

The very first step of "getting started" is NOT how to download and fill in the blanks, which is obvious to anyone whose ever signed up for an account on a computer.  The first step is WHAT DO I NEED TO DOWNLOAD in order to do what I want to do.  Desktop vs browser extension, or both?  How do I "get started"?????

**Comment by fschillingeriv** [comment]
@sumatra54 Point well taken! We're still in the early days of creating our Getting Started material, but this is a good suggestion that we'll work on some content for. In the meantime, to help you specifically:

Which Bitwarden app you choose to use can largely be up to your individual needs & preferences. I, for example, prefer the desktop app because I find the interface's layout really enjoyable to use. That said, a lot of folks prefer the browser extension for it's auto-fill capabilities (which desktop doesn't have today).

There's no reason you can't use both (Bitwarden apps will [keep in-sync](https://bitwarden.com/help/article/vault-sync/), but the long-story-short is that if you need auto-fill, use a Browser Extension.
