### ISSUE TITLE
Add reminder to delete CSV/Export file

### ISSUE THREAD

**Issue by kgheacock** [bitwarden/help#490]
URL: https://bitwarden.com/help/article/import-from-chrome/
After following these steps, the user will have an unencrypted file containing their secrets. This should be deleted (ideally securely) to prevent leakage if a user's computer is ever compromised

**Comment by vachan-maker** [comment]
There is already a reminder
![image](https://user-images.githubusercontent.com/65799568/111860640-e23d2d00-896e-11eb-88f5-850e4ba928ce.png)

**Comment by richb-hanover** [comment]
I agree with the OP. The Import page should post some kind of reminder. 

Anecdote: I got so excited by the successful import that I totally forgot to delete that file from my computer. (In fact, reading this issue is the first thing that reminded me to do it...)

It would be good to add a final (maybe even modal?) step, reminding the person to delete the plaintext file.

**Comment by tgreer-bw** [comment]
Good feedback! @richb-hanover I've captured your feedback, but we do use https://community.bitwarden.com for feature requests. I'll close this issue since the `/help` issue is resolved :-)
