### ISSUE TITLE
bitwarden send: log out and back in to see it

### ISSUE THREAD

**Issue by hussong** [bitwarden/help#510]
Here's my story:

- I read about "bitwarden send" in the news and got excited
- couldn't find it in my account, did a quick google search and landed at https://bitwarden.com/help/article/about-send/
- was still puzzled why I couldn't find it
- looked at the plans to see if I have to upgrade
- went for the good ol' "have you tried turning it off and on again?!", logged out of bitwarden and back in -- and there it was!

Here are my suggestions for https://bitwarden.com/help/article/about-send/

1. Make it clear that "bitwarden send" is available on all accounts, including free ones
2. Make it clear that existing users may have to sign out and back in in order to see "send" in the web vault at https://vault.bitwarden.com/ (this may apply to other apps as well, I have no idea)

Hope this helps!

**Comment by needs-coffee** [comment]
do you keep your browser signed into your web vault at all times? at least for me I sign out of the web vault between uses. 

Send appeared in my apps and extensions without signing out and back in again so that issue may be specific to the web vault. 

This is something that probably no longer needs changed as by now most users have had to sign out and back into the web vault.

Regarding available for all users - the documentation seems to take a stance that it is assumed for all users unless it explicitly states otherwise (i.e. for FIDO2 the first line states this is for premium users).

**Comment by hussong** [comment]
Thanks for following up!

Yes I hadn't logged out in a while when the issue above occurred. I generally don't log out very often on my main machine, I just let the vault lock up by itself.

Hope this helps!

**Comment by needs-coffee** [comment]
Given the length of time that send has been included  as a feature now I don't think changing the documentation for it would change anything at this point as the vast majority of users will have logged out and back in during this timeframe.

For the minority that have not it would likely be something they would try in troubleshooting (like you did). 
I would vote to close this issue. 

@hussong you could create an issue over at https://github.com/bitwarden/web to suggest a prompt to logout when new features are added?

**Comment by fschillingeriv** [comment]
@hussong that's an interesting one! Agree with @needs-coffee that, given the amount of time Send has been in the wild, it's probably not necessary to add the log-back-in tip. Regardless, we'll keep an eye on the next feature release to see if that phenomenon comes up again!

As was also mentioned, we take the "it's available for everyone unless otherwise stated" approach, but this is good food-for-thought regarding whether we should be more explicit about that 🤔 .
