### ISSUE TITLE
Provide information how to delete multiple folders at once

### ISSUE THREAD

**Issue by grivanov** [bitwarden/help#543]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by Greenderella** [comment]
Hi @grivanov,

I'm afraid at the moment it's not possible to delete multiple folders at once, you must follow the indication from the article in order to delete folder one by one: https://bitwarden.com/help/article/folders/#delete-a-folder

If you need further assistance please write us back using our Contact Form: https://bitwarden.com/contact/
