### ISSUE TITLE
About the password generation record

### ISSUE THREAD

**Issue by igotyoubaby** [bitwarden/help#570]
I have a suggestion for using the software. If I don't copy the password generated by the software, then inside the password generation record, it should not record the password generated by the system running automatically. But now it would confuse me as to which password I actually used.

**Comment by eliykat** [comment]
Hi @igotyoubaby. We use GitHub issues as a place to track bugs and other development related issues. (This 'help' repository is actually to manage our help documentation, not to provide end-user support.) The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

That said, I believe we save all the passwords generated because we have no way of knowing whether the generated password has been used. The user might right-click and copy it (which we have no way of tracking) or even write it down somewhere. It's much safer to track everything generated.

This issue will now be closed. Thanks!
