### ISSUE TITLE
What info or categories do mot transfer from 1P to Bitwarden. Which transfer format is preferred. Thanks

### ISSUE THREAD

**Issue by graybushman** [bitwarden/help#705]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by needs-coffee** [comment]
@graybushman - have you looked into or had experience of what categories do or do not transfer and the transfer format used when importing that you can suggest be added to the help page?

**Comment by fschillingeriv** [comment]
There's a custom importer for `.1pif` files available in your Web Vault at  https://vault.bitwarden.com/#/tools/import, which I'd recommend as the preferred format. There's also 1Password-specific `.csv` importers from Mac and Windows (the format's a bit different when exporting from the 1Password desktop app by OS).

I can see from 1Password's documentation (https://support.1password.com/export/) there's a `.txt` format, but I'd recommend avoiding that.

I don't know of anything that'll be dropped in `.1pif` or `.csv` import, but let me know if you've found otherwise and I can get the doc updated.
