### ISSUE TITLE
fingerprint phrase is not safe. Why isnt there 2 factor google authenticator?

### ISSUE THREAD

**Issue by Blaiis** [bitwarden/help#707]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by Blaiis** [comment]
fingerprint phrase is not safe. Why isnt there 2 factor google authenticator?

**Comment by needs-coffee** [comment]
@Blaiis could you clarify what you mean by not safe? The fingerprint phrase is an additional step to validate genuine requests it’s does not replace any existing account security steps

**Comment by Blaiis** [comment]
I found yesterday 2nd google authorization I think so its ok. Thanks
    On Tuesday, August 17, 2021, 08:54:30 AM GMT-3, Joe Campbell ***@***.***> wrote:  
 
 


@Blaiis could you clarify what you mean by not safe? The fingerprint phrase is an additional step to validate genuine requests it’s does not replace any existing account security steps

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by djsmith85** [comment]
Hi @Blaiis we use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
