### ISSUE TITLE
app:mobile - Feature Suggestion: Search Banner instead of Button

### ISSUE THREAD

**Issue by tylerlalima** [bitwarden/help#743]
Hello! This is the first time making a suggestion so please excuse me if the formatting looks a little off! 

I've been using your application full-time as my password manager! It works fantastically! So let me first say how awesome this application is across devices. The 'Nord' theme is also my favorite. Okay, enough gushing, here's what I'd like to suggest for the iOS version of the application:

We currently have a search button on the top right of the application. Trying to quickly find a login credential takes me to a whole new page to 'search vault'. Which adds an extra window that shouldn't really be needed. Instead of having this button, how about we have the search bar as a banner pinned on the top of the main page? I've gone ahead and made a mock up of what this will look like. Looking forward to what you think!

![sample](https://user-images.githubusercontent.com/75288922/134063091-70bfbcbf-bb14-4f2c-b5ee-73ca41b87c77.png)

**Comment by tgreer-bw** [comment]
Hi @tylerlalima! Thank you for the kind words and suggestions!

We actually have an _amazing_ community forum at community.bitwarden.com where we collect feedback and feature requests. We keep Github separate for bug/issue tracking 🐞 

Turns out there are a few folks already in support of this idea! If you'd like to join the fun, feel free to register in the forums and add to the conversation here: https://community.bitwarden.com/t/ios-app-make-search-field-always-show-at-top-of-my-vault-tab-and-auto-focus-it-when-opening-app/2043/

Thanks again for the feedback - we appreciate it!
