### ISSUE TITLE
Include version numbers

### ISSUE THREAD

**Issue by DarkGM** [bitwarden/help#825]
Within bitwarden the version is referred to numerically.
On the release page it is done by date.

Is 2021-12-07 Version 2.24.2 or another version.

Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by fschillingeriv** [comment]
Hey @DarkGM! The reason we don't have version numbers in there right now is because each client app (Web, Mobile, Browser Ext., etc.) is on a different number. That said, this isn't the first time this has been requested so I'm going to see if I can come up with an elegant way to do it.

I assume you're asking about vault.bitwarden.com? In which case, 2021-12-07 is version 2.25.0. You can see version numbers for other clients using the links at the top of the Release Notes page:

![Screen Shot 2021-12-13 at 10 09 42 AM](https://user-images.githubusercontent.com/69817454/145837288-8f856d32-d7c8-4654-89e4-73cd90f0331e.png)

cc @SergeantConfused
